INSERT INTO MPA
VALUES (1, 'G');
INSERT INTO MPA
VALUES (2, 'PG');
INSERT INTO MPA
VALUES (3, 'PG-13');
INSERT INTO MPA
VALUES (4, 'R');
INSERT INTO MPA
VALUES (5, 'NC-17');



INSERT INTO GENRES (GENRE_NAME)
VALUES ('Комедия');
INSERT INTO GENRES (GENRE_NAME)
VALUES ('Драма');
INSERT INTO GENRES (GENRE_NAME)
VALUES ('Мультфильм');
INSERT INTO GENRES (GENRE_NAME)
VALUES ('Триллер');
INSERT INTO GENRES (GENRE_NAME)
VALUES ('Документальный');
INSERT INTO GENRES (GENRE_NAME)
VALUES ('Боевик');