DROP ALL OBJECTS;

CREATE TABLE IF NOT EXISTS GENRES
(
    GENRE_ID   INT         NOT NULL primary key auto_increment,
    GENRE_NAME VARCHAR(40) NOT NULL
);

CREATE TABLE IF NOT EXISTS MPA
(
    MPA_ID INT primary key NOT NULL auto_increment,
    NAME   VARCHAR(40)     NOT NULL
);

CREATE TABLE IF NOT EXISTS FILMS
(
    FILM_ID     INT primary key NOT NULL auto_increment,
    NAME        VARCHAR(40)     NOT NULL,
    DESCRIPTION VARCHAR(200)    NOT NULL,
    DURATION    INT             NOT NULL,
    RELEASE     DATE            NOT NULL,
    MPA_ID      INT REFERENCES MPA (MPA_ID) ON DELETE CASCADE ON UPDATE RESTRICT
);

CREATE TABLE IF NOT EXISTS USERS
(
    USER_ID  INT primary key NOT NULL auto_increment,
    NAME     VARCHAR(200),
    LOGIN    VARCHAR(200)    NOT NULL,
    EMAIL    VARCHAR(200)    NOT NULL,
    BIRTHDAY DATE
);

CREATE TABLE IF NOT EXISTS FILM_GENRES
(
    FILM_ID  INT NOT NULL REFERENCES FILMS (FILM_ID) ON DELETE CASCADE ON UPDATE RESTRICT,
    GENRE_ID INT NOT NULL REFERENCES GENRES (GENRE_ID) ON DELETE CASCADE ON UPDATE RESTRICT
);

CREATE TABLE IF NOT EXISTS LIKES
(
    FILM_ID INT NOT NULL REFERENCES FILMS (FILM_ID) ON DELETE CASCADE ON UPDATE RESTRICT,
    USER_ID INT NOT NULL REFERENCES USERS (USER_ID) ON DELETE CASCADE ON UPDATE RESTRICT
);

CREATE TABLE IF NOT EXISTS FRIENDS
(
    USER_ID   INT     NOT NULL REFERENCES USERS (USER_ID) ON DELETE CASCADE ON UPDATE RESTRICT,
    FRIEND_ID INT     NOT NULL REFERENCES USERS (USER_ID) ON DELETE CASCADE ON UPDATE RESTRICT,
    STATUS    BOOLEAN NOT NULL
);